:honoka:
  :first_name: 穂乃果
  :last_name: 高坂
  :cv: 新田恵海
  :age: 16
  :birth_month: 8
  :birth_day: 3
  :zodiac_sign: 獅子座
  :blood_type: O
  :height: 157
  :bust: 78
  :waste: 58
  :hip: 82
  :favorite_food: いちご
  :dislike_food: ピーマン
  :profile: 16歳。高校2年生。μ'sの発起人。いつも笑顔でとにかく元気が取り柄。直感と思いつきで行動し、一度決めたら猪突猛進の一直線。多少の困難があっても持ち前の超ポジティブシンキングで次々と突破していく。μ'sのエンジンであり牽引者。
:eli:
  :first_name: 絵里
  :last_name: 絢瀬
  :cv: 南條愛乃
  :age: 17
  :birth_month: 10
  :birth_day: 21
  :zodiac_sign: 天秤座
  :blood_type: B
  :height: 162
  :bust: 88
  :waste: 60
  :hip: 84
  :favorite_food: チョコレート
  :dislike_food: 梅干・のり
  :profile: 17歳。高校3年生。生徒会の会長にして、ロシア人のクォーター。頭脳明晰、運動神経抜群、何をやらせてもそつなくこなす。学校でも人気抜群で、責任感が強く、生徒会長を務める。
:kotori:
  :first_name: ことり
  :last_name: 南
  :cv: 内田彩
  :age: 16
  :birth_month: 9
  :birth_day: 12
  :zodiac_sign: 乙女座
  :blood_type: O
  :height: 159
  :bust: 80
  :waste: 58
  :hip: 80
  :favorite_food: チーズケーキ
  :dislike_food: にんにく
  :profile: 16歳。高校2年生。穂乃果の一番の友人。幼馴染で幼稚園の頃からいつも一緒に遊んでいた仲である。穂乃果とは対照的におっとりと柔らかい性格で、勉強もそつなくこなす優等生。おっとりとはしているが芯は強く、物怖じしない。
:umi:
  :first_name: 海未
  :last_name: 園田
  :cv: 三森すずこ
  :age: 16
  :birth_month: 3
  :birth_day: 15
  :zodiac_sign: 魚座
  :blood_type: A
  :height: 159
  :bust: 76
  :waste: 58
  :hip: 80
  :favorite_food: 穂乃果の家のまんじゅう
  :dislike_food: 炭酸飲料
  :profile: 16歳。高校2年生。日舞の家元の家に育ち、凛とした雰囲気を漂わせる大和撫子。子供の頃から弓道で鍛えられ、礼儀作法も完璧な女の子。自分に厳しく、周りにも厳しいという典型。悪事や怠けるといったことが大嫌い。穂乃果、ことりとは幼馴染。
:rin:
  :first_name: 凛
  :last_name: 星空
  :cv: 飯田里穂
  :age: 15
  :birth_month: 11
  :birth_day: 1
  :zodiac_sign: 蠍座
  :blood_type: A
  :height: 155
  :bust: 75
  :waste: 59
  :hip: 80
  :favorite_food: ラーメン！
  :dislike_food: お魚
  :profile: 15歳。高校1年生。体育会系でいつも明るく、くよくよ悩むより体を動かすタイプ。面白そうという理由で何にでも参加してしまう。体育会系だけあって面倒見はよく、いつも幼馴染の花陽の面倒を見ている。何を言われても返事は大きく、きびきび練習する。
:maki:
  :first_name: 真姫
  :last_name: 西木野
  :cv: Pile
  :age: 15
  :birth_month: 4
  :birth_day: 19
  :zodiac_sign: おひつじ座
  :blood_type: AB
  :height: 161
  :bust: 78
  :waste: 56
  :hip: 83
  :favorite_food: トマト
  :dislike_food: みかん
  :profile: 15歳。高校1年生。両親が大病院を経営しているお嬢様。歌が抜群に上手く、ピアノも弾ける待望の一年生。高飛車でプライドが高く、本心を見せるのが苦手。持ち前の度胸で上級生にも強気で渡り合う。実はさみしがりな一面も。
:nozomi:
  :first_name: 希
  :last_name: 東條
  :cv: 楠田亜衣奈
  :age: 17
  :birth_month: 6
  :birth_day: 9
  :zodiac_sign: 双子座
  :blood_type: O
  :height: 159
  :bust: 90
  :waste: 60
  :hip: 82
  :favorite_food: 焼き肉
  :dislike_food: キャラメル
  :profile: 17歳。高校3年生。生徒会副会長。絵里とは対照的にマイペースな性格で、関西弁混じりの独特の口調で話す。クールな雰囲気の絵里とはいいコンビ。大らかさがあり、全メンバー中、実は精神年齢は一番上と思わせる所も。のほほんとしているけれど、意外と策士？
:hanayo:
  :first_name: 花陽
  :last_name: 小泉
  :cv: 久保ユリカ
  :age: 15
  :birth_month: 1
  :birth_day: 17
  :zodiac_sign: 山羊座
  :blood_type: B
  :height: 156
  :bust: 82
  :waste: 60
  :hip: 83
  :favorite_food: 白いごはん
  :dislike_food: なし
  :profile: 15歳。高校1年生。クラスでもあまり目立たない、おとなしい女の子。自信がなく、何をやろうとしても諦めてしまいがち。μ'sに憧れて、凛、真姫と共に入部することになる。凛と仲が良く、いつも一緒にいる。白いご飯が大好物。
:nico:
  :first_name: にこ
  :last_name: 矢澤
  :cv: 徳井青空
  :age: 17
  :birth_month: 7
  :birth_day: 22
  :zodiac_sign: 蟹座
  :blood_type: A
  :height: 154
  :bust: 74
  :waste: 57
  :hip: 79
  :favorite_food: お菓子
  :dislike_food: 辛いもの
  :profile: 17歳。高校3年生。アイドルを目指して日夜励んでいる、正真正銘のアイドルオタク。アイドルを目指している先輩として、穂乃果たちに偉そうに接することもしばしば。その割には失敗も多く意外にドジっ子。「にっこにっこにー」が合い言葉。
