- number: 1
  title: 叶え！私たちの夢——
  description: 東京都千代田区にある伝統校「国立音ノ木坂学院」。ここに通う高校2年の高坂穂乃果は、学校が3年後には廃校になることを知る。廃校を免れるには入学希望者を増やすしかない。そう考えた彼女は親友の南ことりや園田海未と学校の長所を探すが、これといってアピールできるような特徴はなかった。翌朝、穂乃果は人気校のUTX学院を偵察に行き、そこで見たスクールアイドルの姿に衝撃を受ける。そして彼女は学校を救う秘策を思い付くが——。
- number: 2
  title: アイドルを始めよう！
  description: 入学希望者を増やすためにスクールアイドルグループを結成することにした穂乃果たちは、生徒会長の絢瀬絵里の反対を受けるも、初ライブのために講堂の使用許可を得ることに成功。 グループ名は募集することにして、衣装デザインはことり、作詞は海未が担当することに。そして始まるトレーニング。そんな中、穂乃果は歌とピアノが得意な1年生の西木野真姫に作曲を依頼するが断られてしまう。 さらには絵里から逆効果を指摘され、穂乃果は意気消沈してしまうが……。
- number: 3
  title: ファーストライブ
  description: グループ名が「μ's（ミューズ）」に決まり、デビュー曲も完成した穂乃果たち。学校内での認知度も高まり、努力の甲斐あってかアイドルランキングも僅かに上昇して3人は大喜び。そして迎えたライブ当日。穂乃果たちはクラスメイトの協力を得て本番に挑むことに。これまでの練習の日々を思いだし、決意を新たにする穂乃果たち。μ'sのファーストライブがついに始まるが……。
- number: 4
  title: まきりんぱな
  description: 誰もいない講堂で初ライブを終えたμ's。だが３人はいつか大勢の客を前に歌うことを誓う。そのためにはメンバーを５人に増やし、生徒会に部として認めてもらわなければならない。さっそくメンバー募集を始めた穂乃果は、1年生の花陽を勧誘するも逃げられてしまう。しかし花陽は、本心ではアイドルに憧れを抱いていた。親友の凛に勧められるも、決心できず悩み続ける花陽。そんなとき、彼女はメンバー募集のチラシを手にする真姫と遭遇し……。
- number: 5
  title: にこ襲来
  description: 花陽、凛、真姫を迎え総勢6名となったμ's。しかし梅雨入りのために雨天が続き、彼女たちは思うように練習できずにいた。せめて部として認められれば教室が借りられるのに……ここで穂乃果がようやく気付く。すでにμ'sは部を設立する条件である5人を超えていたのだ。さっそく生徒会に申請に行った穂乃果たちだが、この学校には既に「アイドル研究部」なる部が存在し、無闇に部を増やすことはできないと告げられてしまう。やむをえず、穂乃果たちはアイドル研究部との交渉に向かうが……！
- number: 6
  title: センターは誰だ？
  description: 矢澤にこを新メンバーに迎え、正式に部として活動を始めたμ’s。そんな彼女たちを、部活紹介の映像をとるために、生徒会副会長の希が取材することに。一通り取材を終えた希は、ある疑問を穂乃果にぶつける。海未は作詞を担当し、ことりはダンスのステップを考えたりしているが、これといった役割のない穂乃果がなぜリーダーなのか？希の指摘を受け、新リーダーを決めるべく歌とダンスで競うことになったμ'sの面々。はたして新リーダーの座は誰の手に！？
- number: 7
  title: エリーチカ
  description: アイドルの祭典「ラブライブ！」の開催を知った穂乃果たちは早速出場を目指すことに。エントリーの許可を得ようと理事長への直談判を強行した穂乃果たちは、期末テストで赤点をとらないことを条件にエントリーを許される。一方、海未は校門でμ’sのライブ動画に見入る少女に遭遇。なんと動画を撮影してサイトに上げたのは、彼女の姉、絵里だった。絵里が頑なにμ’sの活動を認めようとしない理由がわからず、海未は副会長の希に相談するが――。
- number: 8
  title: やりたいことは
  description: ついに廃校決定！？だがそれは、二週間後のオープンキャンパスの評判次第とのこと。祖母の母校でもある音ノ木坂学院を守るため、オープンキャンパスを成功させる方法を模索する絵里。一方、穂乃果たちもオープンキャンパスに向けて練習を始めるが、絵里の実力を知った海未は、自分たちのダンスのレベルについて思い悩む。そこで海未はこれまでの経緯を穂乃果たちに話し、絵里にダンスを教えてもらうことを提案するが……。
- number: 9
  title: ワンダーゾーン
  description: 絵里と希を迎えて総勢９名となったμ's。新編成で臨んだオープンキャンパスでのライブも好評で、廃校決定はしばらく様子見ということに。一方、μ’sのスクールアイドルランキングは50位にまで上昇していたが、「ラブライブ！」出場の条件である20位以内に入るのは至難の業で、そのためには思い切ったことをすべきと絵里は考える。そんな中、練習の一環でアキバにやってきた穂乃果たちは、スクールアイドルショップでμ'sとは違う衣装で歌うことりの写真を発見してしまい……。
- number: 10
  title: 先輩禁止！
  description: 「ラブライブ！」出場枠選考まで一ヶ月を切ったある日、穂乃果は真姫の家の別荘を借りた合宿を提案。一方、先輩後輩を意識することが障害になると考えた絵里は、この合宿を機にμ's内での「先輩」禁止令を発案する。慣れない会話に緊張する１、２年生。そうして一行は海辺の別荘に到着するが、穂乃果たちは練習そっちのけで海に遊びに行ってしまう。そんな中、真姫だけが皆から離れて一人読書に耽っていた。それに気付いた希は・・・！
- number: 11
  title: 最高のライブ
  description: 夏休みを終えた新学期、μ’sのランキングは「ラブライブ！」出場圏内の19位にまで浮上していた。出場枠が決まるまで残り二週間。各地のスクールアイドルも最後の追い込みに入るはずと、気を引き締めるμ’sの面々。そんな彼女たちの次なる活動は学園祭でのライブだったが、クジに外れて屋上でやることに。それでも、μ'sの集大成的なライブにしようと、俄然張り切る穂乃果。そんな中、海未はことりの様子がおかしいことに気付き･･･。
- number: 12
  title: ともだち
  description: 穂乃果が倒れたことで中止となってしまったμ'sの学園祭ライブ。数日後、療養中の穂乃果は、絵里からμ'sの「ラブライブ！」エントリー辞退を知らされる。やがて学校に復帰した穂乃果であったが、「ラブライブ！」という目標を失いいつもの調子が出ない。一方、彼女達の活動で音ノ木坂学院の入学希望者は急増し、来年度の新入生募集が決定。アイドル研究部は学園存続を祝うパーティーを開くが、その最中、海未の口から衝撃の事実が明かされ……！
- number: 13
  title: μ’s ミュージックスタート！
  description: ことりの悩みに気付けなかった自分を責め、スクールアイドル引退を決意した穂乃果。それを受けてμ'sは活動を休止し、目的を失った穂乃果は海未ともすれ違ってしまう。そんな中、スクールアイドルを続けようと練習に励むにこに素っ気無いながらも励まされ、絵里からは思いもよらぬ告白をされた穂乃果はある決心をする。翌朝、呼び出しに応じて講堂にやってきた海未に、穂乃果は素直な思いを伝える。それを聞いた海未は――。

