- number: 1
  title: もう一度ラブライブ！
  description: 廃校を免れた音ノ木坂学院で、相変わらずの日々を過ごすμ’sのメンバー。そんな彼女たちのもとに、「ラブライブ！」が再び開催されるというニュースが舞い込む。今回は地区予選を勝ち進んだチームが本選に進めるシステムだ。強豪チーム「A-RISE」と地区予選でぶつかることに弱音を吐くも、諦めるのはまだ早いと意気込むメンバーたち。そんな中、穂乃果が「出場しなくてもいいと思う」と言い出して――！？
- number: 2
  title: 優勝をめざして
  description: 「ラブライブ！」に向けて再び走り始めたμ's。そんな矢先、地区予選で歌えるのは未発表の曲に限る、という新しいルールが発表された。そこで、一ヵ月足らずという短い期間で新曲を完成させるべく、9人は山へ合宿に行くことに！宿泊先はもちろん真姫の別荘だ。いつものようにことりが衣装、海未が作詞、真姫が作曲を進めようとするが、3人は地区予選突破のプレッシャーからスランプに陥ってしまい……。
- number: 3
  title: ユメノトビラ
  description: ついに「ラブライブ！」の地区予選が目前に迫ってきた。パフォーマンスをする場所は自由に決められるため、穂乃果は学校にステージを作ろうと提案するが、にこと花陽は、もっとインパクトのあるものにしなければ勝ち抜けないと一蹴する。しかし、学校周辺にはそれに見合う場所がなかなか見つからない。そんな中、穂乃果たちはUTX高校の巨大なモニターに映るA-RISEの堂々とした姿を見て身が引き締まる。そのとき目の前に、本物のA-RISEが現れて――！
- number: 4
  title: 宇宙No.1アイドル
  description: 地区予選を見事突破したμ's。ライバルのA-RISEも同じく地区予選を突破したと知り、ますます気合いが入る。そんななか、なぜかにこが練習に参加せず帰宅してしまう。怪しく思った穂乃果たちはにこを尾行し、スーパーで買い物をしているところを目撃する。追いかけるものの、振り切られてしまうメンバー。釈然としない一同だったが、そんな彼女たちの前を、にこによく似た少女が通りかかった。その少女は、にこの妹だと名乗るのだが！？
- number: 5
  title: 新しいわたし
  description: 2年生が修学旅行へ行っている間、リーダー代理として抜擢された凛。しかし、メンバーからの推薦とは裏腹に、どこか乗り気でなく、戸惑った様子の凛。練習で起こった些細な意見の食い違いも、リーダーだからと判断を迫られるが、うまくまとめることができない。花陽と真姫は凛を励まそうとするが、自分はリーダーに向いていないし、可愛くもないと頑なに言い張る凛。どうやらその原因は小学校の頃の出来事が原因になっているようで……。
- number: 6
  title: ハッピーハロウィーン
  description: 秋葉原のハロウィーンイベントにゲストとして招待されたμ's。「ラブライブ！」で優勝するには、地域の応援も欠かせない。観客の印象に残るパフォーマンスを行い、最終予選の前に少しでもA-RISEとの差を縮めたい。そんなμ’ｓを尻目に、早速インパクト充分にイベントの開幕を盛り上げたA-RISE。先手を取られたμ’sは、自分たちも従来のイメージを変え、強いインパクトを与えなければと思い悩む。すると海未が、やるからには思い切って変える必要があると言い出して――
- number: 7
  title: なんとかしなきゃ！
  description: 身体測定の結果、体重が増えていた穂乃果。海未にだらしないと一喝され、久々にファーストライブの衣装を着てみると……。事実を目の当たりにした穂乃果は、ダイエットを余儀なくされる。それを他人事のように見ていた花陽も同じ状況に陥っていた。一緒に頑張ろうと手を取り合う2人。しかし、生徒会には部活動の予算会議が迫っていた。生徒会の仕事もこなしながらダイエットをしなくてはならない穂乃果だったが――。
- number: 8
  title: 私の望み
  description: 最終予選で歌う曲を決めようとするが、なかなか意見がまとまらないμ’s。そんなとき、希がラブソングの作曲を提案する。メンバーたちは慣れないジャンルに動揺するが、意外にも絵里はそれを支持していた。しかし、試しにラブソングに役立ちそうな場面をシミュレーションしてみたものの、いまいちピンとこない。やはり無理をしないほうがという一同に対し、絵里はもう少し考えてみようと提案し、結局結論は持ち越しに。そんな絵里に真姫は疑問を抱くが――。
- number: 9
  title: 心のメロディ
  description: 最終予選の当日、学校説明会で生徒会からの挨拶をしてから会場へ向かおうとしていた穂乃果たち2年生だったが、雪の影響で交通機関が麻痺し、移動手段を失ってしまう。とにかく会場へ向かおうと3人は雪の中を歩きだすが――。その頃、先に会場に到着したメンバーは、ステージの大きさに圧倒されていた。さらにA-RISEからは勝利宣言され、不安を募らせる6人。果たして穂乃果たちは間に合うのか？そして最終予選の行方は――！？
- number: 10
  title: μ’s
  description: 新年を迎え、初詣にやってきた穂乃果たちは、偶然A-RISEのメンバーと出会い、本大会への激励の言葉をかけられる。そう、東京地区の最終予選は見事μ’sが制したのだ。その本大会に出場するチームは、チーム紹介ページにキャッチフレーズを載せることができるという。μ’sを一言で言い表す言葉がないか思案する穂乃果たちだが、なかなかいい案が出てこない。そんな彼女のもとに、突然A-RISEのリーダーのツバサが現れて――。
- number: 11
  title: 私たちが決めたこと
  description: 雪穂と亜里沙が無事に音ノ木坂学院に合格したことで、μ’sの今後について話し合うことになった9人。誰かがいなくなっても名前を変えずに続けるのがアイドルだというにこと、この9人じゃないとμ’sと言えないという花陽。結論を出せずにいるμ’sの面々だったが、残るメンバーが決めるべきだという絵里の言葉を受け、6人で答えを出すことに。それぞれにμ’sのこれからを考え、眠れぬ夜を過ごすメンバーたちだったが――。
- number: 12
  title: ラストライブ
  description: ラブライブ！が終わったらμ'sはおしまいにする。全員でそう決め、本大会前日を迎えたメンバーたち。いつもと同じように屋上に集まり、和やかな雰囲気のうちに練習を終えるが、こうして9人で練習するのが最後だと思うとなかなか家路につけず、結局穂乃果の提案で最後の夜を学校で一緒に過ごすことに。合宿の時のような雰囲気にはしゃぎながらも、決意を新たに眠りにつく9人。そして翌朝、遂に本大会当日がやってきた――！
- number: 13
  title: 叶え！みんなの夢――
  description: 今日は卒業式。やっと送辞を作り終えた穂乃果は、意気揚々と学校へ向かう。校門前で出会った凛たちとやってきた部室には、トロフィーと旗が。そう、μ'sは見事に優勝を果たしたのだ。卒業式の準備も終わり、ついに本番。穂乃果は、こういうのは苦手だからと、真姫の伴奏で歌を歌い始める。それはいつしか全校生徒による大合唱になっていた。そうして卒業式を終え、9人は最後に一緒に校舎を見て回ることになり――。
